name = "blogger-pwa"
main = "./src/workers/index.ts"
compatibility_date = "2024-06-22"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 8080

[site]
bucket = "./bucket"

[vars]
CF_ENV = "local"

[env.production]
minify = true
routes = [
  # zone_name = "fineshopdesign.com"
  # Replace 'fineshopdesign.com' with your domain name (must be added in Cloudflare Account)
  # e.g.: zone_name = "example.com"
  #
  # pattern = "plus-ui.fineshopdesign.com/app/*"
  # Replace 'plus-ui.fineshopdesign.com' with your blogger subdomain and domain (domain name must be same as zone_name)
  # e.g.: pattern = "www.example.com/app/*"
  { pattern = "plus-ui.fineshopdesign.com/app/*", zone_name = "fineshopdesign.com", custom_domain = false }
]

[env.production.vars]
CF_ENV = "production"
